language: android

android:
  components:
    - extra-google-m2repository
    - extra-android-m2repository
    - platform-tools
    - tools
    - build-tools-28.0.2
    - android-28
    
licenses:
    - 'android-sdk-preview-license-.+'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'

script:
  - echo y | android update sdk -u -a -t tools
  - echo y | android update sdk -u -a -t platform-tools
  - echo y | android update sdk -u -a -t build-tools-28.0.2
  - echo y | android update sdk -u -a -t android-28
  - echo y | android update sdk -u -a -t extra-google-m2repository
  - echo y | android update sdk -u -a -t extra-android-m2repository 
  - ./gradlew build
  - ls app/build/outputs/apk/debug
  - cd app/build/outputs/apk/debug &&  curl --upload-file ./app-debug.apk https://transfer.sh/app-debug.apk && sleep 5